---
# tasks file for myloadbalancer

- name: Installing HAProxy software
  package:
         name: haproxy
         state: present

- name: Configure the configuration file of haproxy
  template:
         src: haproxy.cfg
         dest: /etc/haproxy/haproxy.cfg
  notify:
  - Restart haproxy

- name: Start the service
  service:
         name: haproxy
         state: started

