---
# tasks file for myapache

- name: Installing httpd software
  package:
          name: httpd
          state: present

- name: Installing PHP software
  package:
          name: php
          state: present

- name: Copy the Webpages to the root directory
  template:
          src: index.html
          dest: /var/www/html/index.html
  notify:
  - Restart httpd

  
- name: Start the service
  service:
          name: httpd
          state: started

